name: Publish

on:
  push:
    branches:
      - master
      - staging

jobs:

  s3-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set shared environment variables
        uses: offerzen/action-env-vars-from-ssm@v1
        with:
          path: '/shared/'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ORG_AWS_ACCESS_KEY_ID_GHA }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ORG_AWS_SECRET_ACCESS_KEY_GHA }}
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ROLE_ARN: ${{ secrets.ORG_AWS_ROLE_ARN_GHA_PRODUCTION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID_GHA }}
          aws-secret-access-key: ${{ secrets.ORG_AWS_SECRET_ACCESS_KEY_GHA }}
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.ORG_AWS_ROLE_ARN_GHA_PRODUCTION }}
          role-duration-seconds: 900

      - name: Download global scripts
        uses: actions/download-artifact@v2
        with:
          name: global-files
          path: global/
      
      - name: Download offezen scripts
        uses: actions/download-artifact@v2
        with:
          name: offerzen-files
          path: offerzen/

      - name: Upload scripts to S3 bucket
        env:
          S3_DEPLOY_PATH: "s3://$S3_BUCKET_NAME_OZ_CDN/${{ github.event.repository.id }}"
        run: |
          echo "Uploading JS files to Cloudfront CDN"
          aws s3 sync --no-progress --include *.js --include *.css --content-encoding utf-8 --cache-control no-cache global/ ${{ env.S3_DEPLOY_PATH }}/global
          aws s3 sync --no-progress --include *.js --include *.css --content-encoding utf-8 --cache-control no-cache offerzen/ ${{ env.S3_DEPLOY_PATH }}/offerzen
